# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: true
warnings_are_errors: false

os:
#  - osx
  - linux

r:
#  - oldrel
  - release
  - devel

r_packages:
  - covr

#matrix:
#  exclude:
#    - r: devel
#      os: osx

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"

after_success:
  - travis_wait Rscript -e "covr::codecov()"
