# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false
#warnings_are_errors: false

os:
  - osx
  - linux

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - devtools
  - testthat

matrix:
  exclude:
    - r: devel
      os: osx

script:
  - R CMD build --no-build-vignettes --no-manual .
  - R CMD check --no-build-vignettes --no-manual *tar.gz

after_success:
  - travis_wait Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
